### ISSUE TITLE
RawPOSIX todo

### ISSUE THREAD

**Issue by Yaxuan-w** [JustinCappos/fdtables#3]
- **Error Handling**

Currently, RawPOSIX directly returns an error message and panics when a kernel function fails. We need a better approach to handle such conditions, for example, by extracting error messages and setting errno appropriately.

- **Extracting Reusable Code from GenSockAddr** 

RawPOSIX currently uses only part of the functionalities (layout and conversion) of the `GenSockAddr` data structure. There is a lot of unused code that needs to be cleaned up. We could extract the conversion steps into separate functions to make the code cleaner. Additionally, we might be able to extract the common parts in RawPOSIX and RustPOSIX to form a shared library that could be used in both projects.

- **Cleanup**

Many pieces of code are commented out rather than deleted to facilitate easier debugging. Once the LAMP stack is operational, we need to clean up the codebase.

- **Callback function usage**

RawPOSIX should treat the FDTable interface as a black box. Therefore, the FDTable shouldn’t call `kernel_close` inside the interface. Ideally, RawPOSIX should be able to set up a callback handler before usage. I attempted several methods to achieve this, but all encountered problems. To make things work and save time, I [set up the `kernel_close` inside the interface](https://github.com/JustinCappos/rawposix/blob/589870ae44f958cb28dd8625b03ad24eab50ee6a/src/example_grates/dashmapvecglobal.rs#L103) for now and will revisit this approach later.

**Comment by JustinCappos** [comment]
can you use the register_close_handlers function to set your own handler instead: https://github.com/JustinCappos/rawposix/blob/589870ae44f958cb28dd8625b03ad24eab50ee6a/src/example_grates/dashmapvecglobal.rs#L396-L402

**Comment by JustinCappos** [comment]
Looks like that will fix the problem...
